name: flutter_doc
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_localizations:
    sdk: flutter
  intl:

  # In app update
  upgrader: any

  # Router
  go_router: any

  #  Bloc for state management
  # flutter_bloc: ^3.0.0
  # Router
  # go_router: any
  #  Value equality
  # equatable: any
  #  Functional programming thingies
  # dartz: ^0.10.1
  # Firebase
  # firebase_core: any
  # firebase_messaging: any
  # firebase_crashlytics: any
  # Web Socket
  # web_socket_channel: any

  # ------- Networking ------- #
  # Http Client
  dio: any
  # Cookies
  # dio_cookie_manager: any
  # Image Provider
  # dio_image_provider: any
  
  # Chucker
  chucker_flutter: any
  # ------- End Networking ------- #

  # Cached Image
  cached_network_image: any
  # Bluring view
  flutter_blurhash: any
  #  Json
  # freezed_annotation: any
  # json_annotation: any
  # Webview
  # webview_flutter: any
  # Maps
  # google_maps_flutter: any
  # Video player
  # video_player: any
  # Image Picker
  #  image_picker: any
  # Image cache
  # cached_network_image: any
  # Path provider
  # path_provider: any

  # ------- Secure Preferences ------- #
  #  Local cache
  shared_preferences: any
  #  Secure Storage
  flutter_secure_storage: any
  # ------- End Secure Preferences ------- #

  #   Device info
  device_info_plus: any
  #   Application info
  package_info_plus: any
  #   Connectivity info
  connectivity_plus: any
  #   Device UUID
  uuid: any
  #  Toast
  fluttertoast: any
  #  Logger
  #  logging: any
  # Sharing
  # share_plus: any
  # Launching a URL. Supports web, phone, SMS, and email schemes
  # url_launcher: any
  # auto swith widget by platform
  #  flutter_platform_widgets: any
  # lottie animation
  # lottie: any
  # shimmer loading
  # shimmer: any
  # auto size text
  # auto_size_text: any
  # Camera
  # camera: any
  # DotEnv loader
  # secure_dotenv:
  # flutter_dotenv: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  # build_runner: any
  # secure_dotenv_generator:

  # JSON
  # build_runner: any
  # freezed: any
  # json_serializable: any

  # A flutter utility to easily create flavors in your flutter application
  # flutter_flavorizr: any

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # The following section is flavor to Flutter.

