name: flutter_doc
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_localizations:
    sdk: flutter
  intl:

  ### ------- Navigation ------- ###
  # Router
  go_router: any
  # Launching a URL. Supports web, phone, SMS, and email schemes
  # url_launcher: any
  ### ------- End Navigation ------- ###

  ### ------- Arch/State Management ------- ###
  #  Bloc for state management
  # flutter_bloc: any
  # Provider
  # provider: any
  ### ------- End Arch/State Management ------- ###

  ### ------- Common ------- ###
  # Value equality
  equatable: any
  # In app update
  upgrader: any
  # Device UUID
  uuid: any
  # Toast
  fluttertoast: any
  # Camera
  # camera: any
  # Webview
  # webview_flutter: any
  # Maps
  # google_maps_flutter: any
  # Video player
  # video_player: any
  # Image Picker
  # image_picker: any
  # Path provider
  # path_provider: any
  ### ------- End Common ------- ###
  
  ### ------- Firebase ------- ###
  # Firebase
  # firebase_core: any
  # firebase_messaging: any
  # firebase_crashlytics: any
  ### ------- End Firebase ------- ###

  ### ------- Networking ------- ###
  # Http Client
  dio: any
  # Cookies
  # dio_cookie_manager: any
  # Image Provider
  # dio_image_provider: any
  # Web Socket
  # web_socket_channel: any
  # Cached Image
  cached_network_image: any
  # Chucker
  chucker_flutter: any

  #  Json
  # freezed_annotation: any
  # json_annotation: any
  ### ------- End Networking ------- ###

  ### ------- Secure Preferences ------- ###
  #  Local cache
  shared_preferences: any
  #  Secure Storage
  flutter_secure_storage: any
  ### ------- End Secure Preferences ------- ###

  ### ------- Utilities ------- ###
  # Device info
  device_info_plus: any
  # Application info
  package_info_plus: any
  # Connectivity info
  connectivity_plus: any
  # Sharing
  # share_plus: any
  ### ------- End Utilities ------- ###

  ### ------- Widget ------- ###
  # Bluring view
  flutter_blurhash: any
  # auto size text
  # auto_size_text: any
  # lottie animation
  # lottie: any
  # shimmer loading
  # shimmer: any
  ### ------- End Widget ------- ###
  
  ### ------- Environment ------- ###
  # DotEnv loader
  # secure_dotenv: any
  # flutter_dotenv: any
  ### ------- End Environment ------- ###

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # build_runner: any
  # secure_dotenv_generator:

  ### ------- Networking ------- ###
  # JSON
  # freezed: any
  # json_serializable: any
  ### ------- End Networking ------- ###

  ### ------- Utilities ------- ###
  # flavors
  # flutter_flavorizr: any
  ### ------- End Utilities ------- ###

flutter:
  generate: true
  uses-material-design: true

